
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Madhusha Prasad
 */
public class Calculator extends javax.swing.JFrame {

    String operatorSum;
    String operatorMin;
    String operatorDivi;
    String operatorMulti;
    String dotOper;

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtDisplay = new javax.swing.JTextField();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btnMi = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnMulti = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn = new javax.swing.JButton();
        btnDivi = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnQua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 320, 60));

        btn1.setText("1");
        btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 40));

        btn2.setText("2");
        btn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 80, 40));

        btn3.setText("3");
        btn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 80, 40));

        btnSum.setText("+");
        btnSum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        jPanel1.add(btnSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 80, 40));

        btnMi.setText("-");
        btnMi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 80, 40));

        btn6.setText("6");
        btn6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, 40));

        btn5.setText("5");
        btn5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, 40));

        btn4.setText("4");
        btn4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, 40));

        btnMulti.setText("x");
        btnMulti.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiActionPerformed(evt);
            }
        });
        jPanel1.add(btnMulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 80, 40));

        btn9.setText("9");
        btn9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 80, 40));

        btn8.setText("8");
        btn8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 80, 40));

        btn7.setText("7");
        btn7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 40));

        jButton13.setText("+/-");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, 40));

        btn0.setText("0");
        btn0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 80, 40));

        btn.setText(".");
        btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 80, 40));

        btnDivi.setText("/");
        btnDivi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiviActionPerformed(evt);
            }
        });
        jPanel1.add(btnDivi, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 40));

        btnClear.setText("c");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 40));

        btnQua.setText("=");
        btnQua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnQua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 160, 40));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 350, 390));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaActionPerformed
        getAnswer();
    }//GEN-LAST:event_btnQuaActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String none = txtDisplay.getText() + 1;
            txtDisplay.setText(none);
        } else {
            txtDisplay.setText("1");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtDisplay.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String two = txtDisplay.getText() + 2;
            txtDisplay.setText(two);
        } else {
            txtDisplay.setText("2");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String three = txtDisplay.getText() + 3;
            txtDisplay.setText(three);
        } else {
            txtDisplay.setText("3");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String four = txtDisplay.getText() + 4;
            txtDisplay.setText(four);
        } else {
            txtDisplay.setText("4");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String five = txtDisplay.getText() + 5;
            txtDisplay.setText(five);
        } else {
            txtDisplay.setText("5");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String six = txtDisplay.getText() + 6;
            txtDisplay.setText(six);
        } else {
            txtDisplay.setText("6");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String seven = txtDisplay.getText() + 7;
            txtDisplay.setText(seven);
        } else {
            txtDisplay.setText("7");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String eight = txtDisplay.getText() + 8;
            txtDisplay.setText(eight);
        } else {
            txtDisplay.setText("8");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String nine = txtDisplay.getText() + 9;
            txtDisplay.setText(nine);
        } else {
            txtDisplay.setText("9");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String zero = txtDisplay.getText() + 0;
            txtDisplay.setText(zero);
        } else {
            txtDisplay.setText("0");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String sum = txtDisplay.getText() + "+";
            txtDisplay.setText(sum);
            operatorSum = "+";
        }
    }//GEN-LAST:event_btnSumActionPerformed

    private void btnMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String min = txtDisplay.getText() + "-";
            txtDisplay.setText(min);
            operatorMin = "-";
        }
    }//GEN-LAST:event_btnMiActionPerformed

    private void btnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String multi = txtDisplay.getText() + "x";
            txtDisplay.setText(multi);
            operatorMulti = "*";
        }
    }//GEN-LAST:event_btnMultiActionPerformed

    private void btnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiviActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String divi = txtDisplay.getText() + "/";
            txtDisplay.setText(divi);
            operatorDivi = "/";
        }
    }//GEN-LAST:event_btnDiviActionPerformed

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        if (!(txtDisplay.getText().trim().isEmpty())) {
            String btnDot = txtDisplay.getText() + ".";
            txtDisplay.setText(btnDot);
            dotOper = ".";
        }
    }//GEN-LAST:event_btnActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (txtDisplay.getText().length() > 0) {

            double text = Double.parseDouble(txtDisplay.getText());
            double y = -1 * text;
            txtDisplay.setText(String.valueOf(y));
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void getAnswer() {
        if (txtDisplay.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        } else {
            if ("+".equals(operatorSum)) {
                String textCont = txtDisplay.getText();
                String[] split = textCont.split("\\+");

                int sum = 0;
                for (int i = 0; i < split.length; i++) {
                    sum += Integer.parseInt(split[i]);
                }
                txtDisplay.setText(String.valueOf(sum));
                operatorSum = null;
            } else if ("-".equals(operatorMin)) {
                String textCont = txtDisplay.getText();
                String[] split = textCont.split("\\-");

                int sum = Integer.parseInt(split[0]);
                for (int i = 1; i < split.length; i++) {
                    sum -= Integer.parseInt(split[i]);
                    System.out.println(split[i]);
                }
                txtDisplay.setText(String.valueOf(sum));
                operatorMin = null;
            } else if ("*".equals(operatorMulti)) {
                String textCont = txtDisplay.getText();
                String[] split = textCont.split("x");

                int sum = Integer.parseInt(split[0]);
                for (int i = 1; i < split.length; i++) {
                    sum *= Integer.parseInt(split[i]);
                    System.out.println(split[i]);
                }
                txtDisplay.setText(String.valueOf(sum));
                operatorMulti = null;
            } else if ("/".equals(operatorDivi)) {
                String textCont = txtDisplay.getText();
                String[] split = textCont.split("/");

                int sum = Integer.parseInt(split[0]);
                for (int i = 1; i < split.length; i++) {
                    sum /= Integer.parseInt(split[i]);
                    System.out.println(split[i]);
                }
                txtDisplay.setText(String.valueOf(sum));
                operatorDivi = null;
            }
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivi;
    private javax.swing.JButton btnMi;
    private javax.swing.JButton btnMulti;
    private javax.swing.JButton btnQua;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDisplay;
    // End of variables declaration//GEN-END:variables
}
